#!/bin/bash
# Lädt ein Bild auf imgur hoch und legt den Link in die Zwischenablage
#
# Author: Michael Koch (m.koch<AT>emkay443<DOT>de)
# Version: 2013-08-11_01
# Lizenz: Copyleft

client_id="0000000000000000000000"

function parse_json() {
	echo $1 | \
	sed -e 's/[{}]/''/g' | \
	sed -e 's/", "/'\",\"'/g' | \
	sed -e 's/" ,"/'\",\"'/g' | \
	sed -e 's/" , "/'\",\"'/g' | \
	sed -e 's/","/'\"---SEPERATOR---\"'/g' | \
	awk -F=':' -v RS='---SEPERATOR---' "\$1~/\"$2\"/ {print}" | \
	sed -e "s/\"$2\"://" | \
	tr -d "\n\t" | \
	sed -e 's/\\"/"/g' | \
	sed -e 's/\\\\/\\/g' | \
	sed -e 's/^[ \t]*//g' | \
	sed -e 's/^"//'  -e 's/"$//'
}

# Abhängigkeiten prüfen
if [[ ! "$(which curl)" ]]; then toInst=$toInst" curl"; fi

# Wenn alles okay: Hochladen und Link in Zwischenablage legen
if [[ -z $toInst ]]; then
	SAVEIFS=$IFS
	for file in "$@"; do
		notify-send --hint=int:transient:1 "Upload" "Das Bild wird hochgeladen..."
		# Versuche das Bild hochzuladen (via curl) und lege die Rückgabe auf die Var. $TEXT
		TEXT=$(curl -H "Authorization: Client-ID $client_id" -F "image"=@"$file" https://api.imgur.com/3/upload.json);
		TEXT=$(parse_json "$TEXT" link | sed 's/\\//g')
		echo -e "$TEXT" | xclip -sel clip
		notify-send --hint=int:transient:1 "Imgur Upload" "Upload erfolgreich.\n\nLink: <a href='$TEXT'>$TEXT</a>\n\nDer Link zu dem Bild liegt in der Zwischenablage."
		play /usr/share/sounds/freedesktop/stereo/complete.oga
	done
	IFS=$SAVEIFS
else
	# Abhängigkeitsprobleme: Nutzer darüber aufmerksam machen.
	notify-send "FEHLER!" "Abhängigkeitsprobleme!"
	echo "Folgende Pakete fehlen auf Ihrem System:$toInst"
	zenity --warning --title "Abhängigkeitsprobleme" --text "Folgende Pakete fehlen auf Ihrem System:\n$toInst" 0 0
	exit 1
fi
exit 0
