#!/bin/bash
# Fetches a random wallpaper from /r/earthporn
# and sets xfdesktop's wallpaper to it
#
# Author: Michael Koch (emkay443) (and others on reddit: http://redd.it/25wkxa)
# Version: 2016-01-08_1
# License: GPL v3

# get XDG variables
. $HOME/.config/user-dirs.dirs

# configuration
wp_file=$XDG_PICTURES_DIR/wpotd
random=true
monitors=( HDMI-0 DVI-I-1 )
workspaces=( 0 1 )
subreddit="earthporn" # i.e. wallpapers, earthporn, cats, awww
useragent="Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1"

# helper variable
if $random; then
	url=$(curl -A "$useragent" -s http://www.reddit.com/r/$subreddit/.rss | grep -o "http://i.imgur.com/[/a-zA-Z0-9.]\+" | shuf -n 1)
else
	url=$(curl -A "$useragent" -s http://www.reddit.com/r/$subreddit/.rss | grep -o "http://i.imgur.com/[/a-zA-Z0-9.]\+" | head -1)
fi
export DISPLAY=:0

# download image
wget -O $wp_file "$url"

# make sure, DBUS is loaded correctly (make this script work with cron)
if [ -z "${DBUS_SESSION_BUS_ADDRESS}" ] ; then
	. ${HOME}/.dbus/session-bus/`ls -rt ${HOME}/.dbus/session-bus/ | tail -1`
        export DBUS_SESSION_BUS_ADDRESS
fi

if [ "$(pidof xfdesktop)" ]; then
	for mon in "${monitors[@]}"; do
		for ws in "${workspaces[@]}"; do
			# set xfdesktop's wallpaper and refresh
			xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor$mon/workspace$ws/last-image -s $wp_file
		done
	done
	xfdesktop --reload
elif [ "$(pidof i3)" ]; then
	feh --bg-fill $wp_file
fi

